# Generated by Django 5.2.3 on 2025-12-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional comments or notes about the review', null=True),
        ),
    ]
