# Generated by Django 5.2.3 on 2025-12-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
